version: "3.8"
services:
  web:
    image: "parandzem/front:eb8f109"
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-backend
  api:
    image: "parandzem/back:8012f0c"
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks: 
     - network-backend
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    env_file: docker.env
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
       - 27117:27017

networks:
  network-backend:

volumes: 
  mongodb_data:
