version: "3.8"
services:
  web:
    image: "parandzem/front:blabla"
    env_file: front.env
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-backend
  api:
    image: "parandzem/back:blabla"
    env_file: back.env
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks: 
     - network-backend
  
  mongo:
    image: mongo
    env_file: docker.env
    restart: always
    volumes: 
      - mongodb_data:/data/db
    ports:
       - 27017:27017
networks:
  network-backend:

volumes: 
  mongodb_data:
